name: Integration Tests

on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    environment: integration
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify a Node.js version

      # This is to force nx arch-specific packages to correctly install
      # This is to work around https://github.com/npm/cli/issues/4828
      - name: Remove package-lock.json
        run: rm -f package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run Integration Tests
        run: |
          lerna run test:integration
        env:
          ZEEBE_ADDRESS: ${{ secrets.ZEEBE_ADDRESS }}
          ZEEBE_CLIENT_ID: ${{ secrets.ZEEBE_CLIENT_ID }}
          ZEEBE_AUTHORIZATION_SERVER_URL: ${{ secrets.ZEEBE_AUTHORIZATION_SERVER_URL }}
          ZEEBE_CLIENT_SECRET: ${{ secrets.ZEEBE_CLIENT_SECRET }}
          ZEEBE_TOKEN_AUDIENCE: ${{ secrets.ZEEBE_TOKEN_AUDIENCE }}
          CAMUNDA_CREDENTIALS_SCOPES: ${{ secrets.CAMUNDA_CREDENTIALS_SCOPES }}
          CAMUNDA_OAUTH_URL: ${{ secrets.CAMUNDA_OAUTH_URL }}
          CAMUNDA_TASKLIST_BASE_URL: ${{ secrets.CAMUNDA_TASKLIST_BASE_URL }}
          CAMUNDA_OPERATE_BASE_URL: ${{ secrets.CAMUNDA_OPERATE_BASE_URL }}
          CAMUNDA_OPTIMIZE_BASE_URL: ${{ secrets.CAMUNDA_OPTIMIZE_BASE_URL }}
