name: Tag and publish a new version

on:
  workflow_run:
    workflows:
      [
        "Single Tenant Integration Tests",
        "Multitenant Integration Tests",
        "SaaS Integration Tests",
      ]
    types:
      - completed

jobs:
  tag-and-publish:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'alpha')
    environment:
      name: publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Install
        run: npm ci --ignore-scripts
      - name: Build
        run: npm run build
      - name: Build Docs
        run: npm run docs
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
