on: [push, pull_request]

jobs:
  local-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      # Workaround for https://github.com/actions/runner-images/issues/2821
      - name: disable and stop mono-xsp4.service
        run: |
          sudo systemctl stop mono-xsp4.service
          sudo systemctl disable mono-xsp4.service

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker/docker-compose.yml up -d

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify a Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Integration Tests
        run: |
          lerna run test:local-integration
        env:
          ZEEBE_SECURE_CONNECTION: false
          ZEEBE_ADDRESS: localhost:26500
          ZEEBE_CLIENT_ID: zeebe
          ZEEBE_AUTHORIZATION_SERVER_URL: http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token
          ZEEBE_CLIENT_SECRET: zecret
          ZEEBE_TOKEN_AUDIENCE: zeebe.camunda.io
          CAMUNDA_CREDENTIALS_SCOPES: Zeebe,Tasklist,Operate,Optimize
          CAMUNDA_OAUTH_URL: http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token
          CAMUNDA_TASKLIST_BASE_URL: http://localhost:8082
          CAMUNDA_OPERATE_BASE_URL: http://localhost:8081
          CAMUNDA_OPTIMIZE_BASE_URL: http://localhost:8081

      - name: Cleanup
        if: always()
        run: docker-compose -f docker/docker-compose.yml down
